local_backend: true

backend:
  name: git-gateway

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    preview_path: "stories/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["News", "Story", "Explainer"], default: "Story" }
      - { label: "External Link", name: "externalUrl", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image", hint: "Fallback image if desktop or mobile image is not specified"}
      - { label: "Featured Image: Desktop mode", name: "imageDesktop", widget: "image", required: false, hint: "Optional image used on screens 1024px and wider"}
      - { label: "Featured Image: Mobile mode", name: "imageMobile", widget: image, required: false, hint: "Optional image used on screens smaller than 768px"}
      - { label: "Image Credit", name: "credit", widget: "string", required: false }
      - { label: "Show in Featured Story", name: "featured", widget: "boolean", default: false }
      - { label: "Show in More Stories", name: "moreStories", widget: "boolean", default: false }
      - { label: "Published Date", name: "publishedAt", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "facts"
    label: "Facts"
    folder: "content/facts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", default: 0 }

  - name: "home"
    label: "Homepage"
    files:
      - name: "featuredSection"
        label: "Featured Section"
        file: "content/settings/featured-section.yml"
        fields:
          - label: "Headline Text"
            name: "headline"
            widget: "string"
            default: "Our mission is to build a future which our vets can be supported"

          - label: "Background Color"
            name: "backgroundColor"
            widget: "color"

          - label: "Text Color"
            name: "textColor"
            widget: "color"

      - name: "moreStoriesSection"
        label: "More Stories Section"
        file: "content/settings/more-stories-section.yml"
        fields:
          - label: "Headline Text"
            name: "headline"
            widget: "string"
            default: "Our work to reverse nature loss and conserve biodiversity has never been more urgent"

          - label: "Background Color"
            name: "backgroundColor"
            widget: "color"

          - label: "Text Color"
            name: "textColor"
            widget: "color"

      - name: "factsSection"
        label: "Facts Section"
        file: "content/settings/facts-section.yml"
        fields:
          - label: "Headline Text"
            name: "headline"
            widget: "string"
            default: "Our Impact is transformative"

          - label: "Subheader Text"
            name: "subheader"
            widget: "string"
            default: "Every dollar you give makes a difference for our community."

          - label: "Background Color"
            name: "backgroundColor"
            widget: "color"

          - label: "Text Color"
            name: "textColor"
            widget: "color"


  - name: "contact"
    label: "Contact Page"
    files:
      - name: "contactPage"
        label: "Contact Page"
        file: "content/settings/contact-page.yml"
        fields:
          - label: "Headline Text"
            name: "headline"
            widget: "string"
            default: "Contact"

          - label: "Subheader Text"
            name: "subheader"
            widget: "text"
            default: "Submit a general question to our support team or explore all options below"
            
          - label: "Contact Info"
            name: "contactInfo"
            widget: "list"
            summary: "{{fields.label}}: {{fields.value}}"
            fields:
              - label: "Label"
                name: "label"
                widget: "string"

              - label: "Value"
                name: "value"
                widget: "string"
              
              - label: "Link"
                name: "href"
                widget: "string"
                required: false

          
          