local_backend: true

backend:
  name: git-gateway

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    preview_path: "stories/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Credit", name: "credit", widget: "string", required: false }
      - { label: "Featured Story", name: "featured", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }