local_backend: true

backend:
  name: git-gateway

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    preview_path: "stories/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["News", "Story", "Explainer"], default: "Story" }
      - { label: "External Link", name: "externalUrl", widget: "string", required: false }
      - { label: "Display Image", name: "image", widget: "image" }
      - { label: "Image Credit", name: "credit", widget: "string", required: false }
      - { label: "Show in Featured Story", name: "featured", widget: "boolean", default: false }
      - { label: "Show in More Stories", name: "moreStories", widget: "boolean", default: false }
      - { label: "Published Date", name: "publishedAt", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "facts"
    label: "Facts"
    folder: "content/facts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Order", name: "order", widget: "number", default: 0 }